#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::Build::CreateLinks  qw(:all);


#--------------------------------------------------
# actions for nethserver-ligthsquid-update event
#--------------------------------------------------

my $event = "nethserver-lightsquid-update";

event_actions($event, qw(
              initialize-default-databases 00
              nethserver-httpd-admin-asyncreload 99
));
templates2events("/etc/httpd/conf.d/lightsquid.conf",  $event);
templates2events("/etc/httpd/admin-conf.d/lightsquid.conf",  $event);
templates2events("/etc/lightsquid/lightsquid.cfg",  $event);
event_services($event, 'httpd' => 'reload');


#--------------------------------------------------
# actions for nethserver-ligthsquid-save event
#--------------------------------------------------

$event = "nethserver-ligthsquid-save";

templates2events("/etc/lightsquid/lightsquid.cfg",  $event);


exit;
